# File Name     : theme.properties
# Version       : v0.1.1
# Created       : 2026-06-25
# Last Modified : 2026-06-25
# Author        : Nouramon Alvestrasza
# Organization  : Alvestrasza Corporation
# Description   : Keycloak login theme declaration for the A-Corp corporate login page.

parent=keycloak
import=common/keycloak
styles=css/login.css css/acorp-login.css
locales=de,en
