# File Name     : theme.properties
# Version       : v0.1.0
# Created       : 2026-06-25
# Last Modified : 2026-06-25
# Author        : Nouramon Alvestrasza
# Organization  : Alvestrasza Corporation
# Description   : Keycloak login theme declaration for the A-Corp corporate login page.

parent=keycloak.v2
import=common/keycloak
styles=css/acorp-login.css
locales=de,en
